config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "cocktails#index"
  resources :cocktails do
    resources :doses
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :photo, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  mount_uploader :photo, PhotoUploader

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates_uniqueness_of :ingredient, scope: :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses
  has_many :cocktails, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save!
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @dose = Dose.find(params[:id])
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "edit cockktail", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<div class="container">

  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1462539405390-d0bdb635c7d1?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=7436b104d69a80e03757d8341f13665f&auto=format&fit=crop&w=1093&q=80');">
    <div class="banner-content">
      <h1>Welcome to Cocktail Mixer</h1>
      <p>The best amateur mixer site around</p>
      <%= link_to "Submit a cocktail", new_cocktail_path, class: "btn btn-primary btn-lg" %>

    </div>
  </div>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card card-mid-size"
          style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
                 url('<%= cl_image_path cocktail.photo %>')">
          <!-- <div class="card-category"> <%= cocktail.name %> </div> -->
          <div class="card-description">
            <h2><%= link_to cocktail.name, cocktail, class: "banner-link" %></h2>
            <!-- <p>Very cool stuff, useful and smart</p> -->
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Submit your cocktail!</h1>
<p>Fill out the form to submit your cocktail</p>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "add cockktail", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<div class="container">


  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 show-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
                 url('<%= cl_image_path @cocktail.photo %>')">
        <div class="card-description">
          <h2><%= link_to @cocktail.name, @cocktail, class: "banner-link" %></h2>
            <!-- <p>Very cool stuff, useful and smart</p> -->
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 show-card">
      <h3>Ingredients</h3>
      <% @cocktail.doses.each do |dose| %>
        <ul>
          <li><%= dose.description %> of <%= dose.ingredient.name %> </li>
          <li><%= link_to "remove a dose", dose_path(dose), method: :delete %></li>
        </ul>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-6 show-card">
      <h3>Menu Options</h3>
      <ul>
        <li><%= link_to "back to cocktails", cocktails_path %></li>
        <li><%= link_to "edit the cocktail", edit_cocktail_path(@cocktail) %></li>
        <li><%= link_to "add a dose", new_cocktail_dose_path(@cocktail) %></li>
      </ul>
    </div>
  </div>
</div>

app/views/doses/edit.html.erb
edit.html.erb

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient  %>
  <%= f.input :description %>
  <%= f.submit "add dose", class: "btn btn-primary" %>
<% end %>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient  %>
  <%= f.input :description %>
  <%= f.submit "add dose", class: "btn btn-primary" %>
<% end %>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

<%= @cocktails.dose.each do |dose| %>
  <%= dose %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="navbar-wagon">
      <!-- Logo -->
      <%= link_to root_path do %>
        <%= image_tag("layout/logo.png", alt: "cocktail logo", class: "avatar") %>
      <% end %>

      <!-- Right Navigation -->
      <div class="navbar-wagon-right hidden-xs hidden-sm">
        <%= link_to "New Cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <!-- Profile picture with dropdown list -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <img src="https://kitt.lewagon.com/placeholder/users/tgowgates" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li><a href="#">Profile</a></li>
              <li><a href="#">Dashboard</a></li>
              <li><a href="#">Log Out</a></li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Dropdown appearing on mobile only -->
      <div class="navbar-wagon-item hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><a href="#">Host</a></li>
            <li><a href="#">Trips</a></li>
            <li><a href="#">Messagese</a></li>
          </ul>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>